# Generated by Django 2.2.12 on 2022-12-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Categories',
        ),
    ]
