# Generated by Django 2.2.12 on 2022-12-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
                ('p_category', models.CharField(max_length=100)),
                ('p_brand', models.CharField(max_length=100)),
                ('p_img', models.ImageField(upload_to='pics')),
                ('p_des', models.TextField()),
                ('p_price', models.FloatField()),
                ('p_offer', models.BooleanField(default=False)),
            ],
        ),
    ]
