# Generated by Django 2.2.12 on 2022-12-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='p_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
