# Generated by Django 2.2.12 on 2022-12-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review_p_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Reviews',
        ),
    ]
