# Generated by Django 2.2.12 on 2022-12-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cart_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('p_img_url', models.URLField()),
                ('p_name', models.CharField(max_length=200)),
                ('p_price', models.FloatField()),
                ('p_date', models.DateField()),
                ('p_qty', models.IntegerField()),
            ],
        ),
    ]
