# Generated by Django 2.2.12 on 2022-12-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_orders_p_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='p_status',
            field=models.BooleanField(default=True),
        ),
    ]
