# Generated by Django 2.2.12 on 2022-12-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_orders_p_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='new', max_length=200),
        ),
    ]
