# Generated by Django 2.2.12 on 2022-12-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('cancel', 'cancel')], default='new', max_length=200),
        ),
    ]
