# Generated by Django 2.2.12 on 2022-12-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20221220_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug_id',
            field=models.SlugField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
