# Generated by Django 2.2.12 on 2022-12-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_products_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='slug_id',
        ),
    ]
